### ISSUE TITLE
downloading multiple files in different folders

### ISSUE THREAD

**Issue by ztren** [SamueleTorregrossa/vsc-download-compressed#1]
When selecting multiple files separately, only the last file I selected is downloaded. Downloading the whole folder works, but it's not what I intended to do. 

Remote: Linux
Local device: MacOS

Anyways thank you so much for your extension which saves me a lot of time downloading things with vscode ssh without having to open FileZilla.

**Comment by SamueleTorregrossa** [comment]
Thank you very much for the feedback!
I just added support for multi-file download, hope it helps
